version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg18
    container_name: postgres_with_vector
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rag
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  postgres-data: