version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg18
    container_name: postgres_with_vector
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rag
    ports:
      - "5433:5432"
    volumes:
      - pg-vector-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  pg-vector-data: